# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Diana Fernanda Castillo Rebolledo
title: Computer Engineering Student
email: castillo.diana2260@gmail.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: CastilloDiana_8
github_username:  diana-castillo
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: cst.diana_
linkedin_username: diana-castillo22
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Diana, I'm a Computer Engineering student in my last semester and at the same time I work as a Programming Intern. I have been studying computing for 9 years and I have learned different programming skills, and with the development of several projects and tasks I have also acquired soft skills necessary to be a better programmer such as team work, adaptability, problem solving and time management.
  
  The programming languages that I currently have the most experience working with are: <mark>Python</mark>, <mark>Javascript</mark>, <mark>PHP</mark>, <mark>SQL</mark> and <mark>C/C++</mark>.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Change Maze
        link: changemaze.creavideojuegos.org
        # link_text: Project Website
        additional_links:
          - title: diana-castillo/Change-Maze
            icon: fab fa-github
            url: github.com/diana-castillo/Change-Maze-Admin
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          I made this project as a final project in my career, it started as an experiment for a teacher's thesis and over time it grew. This project consists in a web game to detect resistance to change in programming students and professional programmers, and obtain statistics about that skill. It was developed in <mark>Javascript</mark>, <mark>Phaser</mark>, <mark>PHP</mark> and <mark>MySQL</mark>.

      - layout: top-middle
        title: Votting App
        # link_text: Project Website
        additional_links:
          - title: diana-castillo/Proy-ft
            icon: fab fa-github
            url: github.com/diana-castillo/Proy-ft
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          This is my final project for the Fault Tolerant Computing class, it consists in a web application to answer a survey about what people prefer: dogs or cats. The difficulty of this project was develop the application with an architecture based in microservices, but it was solved very well and the project was deployed in a Sandbox environment of Red Hat Openshift. It was developed in <mark>Javascript</mark>, <mark>Python</mark>, <mark>Node.js</mark> and <mark>PostgreSQL</mark>.

      - layout: top-middle
        title: App Mis Discos
        # link_text: Project Website
        additional_links:
          - title: diana-castillo/discos-App
            icon: fab fa-github
            url: github.com/diana-castillo/discos-App
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          This mobile app was made as final project for the Databases class. It's a simple app that displays information about music albums, this data is stored in a SQL database and is retrieved with a CRUD using the RESTFul API architecture. This project was developed in <mark>Python</mark>, <mark>Flask</mark>, <mark>Typescript</mark> and <mark>MySQL</mark>.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: PABS
        # link_text: boringcompany.com
        sub_title: Programming Intern
        caption: July 2023 - Present
        description: | # this will include new lines to allow paragraphs
          PABS is a company with different projects, and I've been working here as a programming intern. I've been part of two software projects, first I helped to make some updates for a website to manage Funeraria Latinoamericana, and later I changed to another project about a website for a supermarket chain called JesMart and I've been working on it at the moment. I work with: <mark>PHP</mark>, <mark>Javascript</mark> and <mark>MySQL</mark>.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Universidad de Guadalajara
        caption: 2019 - Present
        sub_title: Computer Engineering
        description: | # this will include new lines to allow paragraphs
          During my degree at Universidad de Guadalajara I mainly have been focusing on software development and the principles of programming, but I also have learned a lot of key skills such as team work, problem resolution and adaptation to change, the same skills that I use to my advantage in my day to day work.      
      
      - layout: left
        title: Escuela Politécnica Ing. Jorge Matute Remus
        caption: 2015 - 2019
        sub_title: Professional Technologist in Computer Science
        description: | # this will include new lines to allow paragraphs
          During my time at Escuela Politécnica I obtained basic skills about programming and computing. At that point I decided that I wanted to continue learning about programming and technology, specially because I discovered that I like to solve programming problems.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in software development some of my other interests and hobbies are related with art and creativity such as pencil drawing and watercolor painting, digital drawing of photos, and photography of landscape and sunsets. Doing this kind of activities relaxes me a lot, in addition to the fact that I pay a lot of attention to details.

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
